meta_product_name: "Fdbckr"
meta_title: "Fdbckr - Create. Collaborate. Control."
meta_description: "The exclusive social platform to share your art (in progress) with a selected group of people to get feedback and improve your creative work."
meta_image: "cover.png"
twitter_account: "@fdbckr"   # required for Twitter Cards